const jokesList = [
  "I asked the surgeon if I could administer my own anesthetic, they said: go ahead, knock yourself out.",
  "Why does Norway have barcodes on their battleships? So when they get back to port, they can Scandinavian.",
  "Why did the miner get fired from his job? He took it for granite...",
  `Q: What did the spaghetti say to the other spaghetti? \n A: Pasta la vista, baby!`,
  `What do you call an eagle who can play the piano?\n Talonted!`,
  `I think circles are pointless.`,
  `Sore throats are a pain in the neck!`,
  `My boss told me to have a good day. So I went home...`,
  `Why is there always a gate around cemeteries? \n Because people are always dying to get in.`,
  `In my career as a lumberjack I cut down exactly 52,487 trees.\n I know because I kept a log.`,
  `What lies at the bottom of the ocean and twitches? A nervous wreck.`,
  `What did the judge say to the dentist? Do you swear to pull the tooth, the whole tooth and nothing but the tooth?`,
  `A man tried to sell me a coffin today. I told him that's the last thing I need.`,
  `Why are mummys scared of vacation? They're afraid to unwind.`,
  `Why did the feline fail the lie detector test? Because he be lion.`,
  `Where do rabbits go after they get married? On a bunny-moon.`,
  `What's black and white and read all over? The newspaper.`,
  `I went to a book store and asked the saleswoman where the Self Help section was, she said if she told me it would defeat the purpose.`,
  `Our wedding was so beautiful, even the cake was in tiers.`,
  `What do you get when you cross a bee and a sheep?\n A bah-humbug.`,
  `I’m reading a book on the history of glue – can’t put it down.`,
  `What do you call a crowd of chess players bragging about their wins in a hotel lobby? Chess nuts boasting in an open foyer.`,
  `My cat was just sick on the carpet, I don’t think it’s feline well.`,
  `What is the least spoken language in the world? Sign Language`,
];

export default jokesList;
